name: Process IP List from Remote URL

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  process-ipsum:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # 确保有写入权限

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 关键！防止覆盖认证信息

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Create Results Directory
        run: |
          rm -rf results || true
          mkdir -p results

      - name: Show Current Time (for debug)
        run: date -u

      - name: Download and Process IP List
        run: python process_ipsum.py https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt

      - name: Configure Git and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用自动生成的令牌
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # 检查变更
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected. Committing and pushing..."
            git add results/*.txt
            git commit -m "Update processed IP lists $(date +'%Y-%m-%d %H:%M:%S') UTC"
            git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
